vivado_pr	:
	vivado -source vivado_flow_pr.tcl
#	vivado -mode batch -source vivado_flow_pr.tcl


vivado_nopr	:
	vivado -mode batch -source vivado_flow_nopr.tcl
	

clean_all	:
	rm -rf *.jou *.txt *.log .gen .srcs ../project/* ../outputDir/* .Xil


clean	:
	rm -rf *.jou *.txt *.log .gen .srcs .Xil
